version: "3"
services:
  build_app:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - ./for_warnic:/mnt/build
      - ./build/boxfuse-sample-java-war-hello-master:/opt/boxfuse
volumes:
  ./for_warnic:
  ./build/boxfuse-sample-java-war-hello-master:
