version: "3"
services:
  build_app:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./for_warnic
        target: /mnt
      - type: bind
        source: ./build/boxfuse-sample-java-war-hello-master
        target: /opt