version: "3"
services:
  build_app:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: ./for_warnic
        target: /mnt/build
      - type: volume
        source: ./build/boxfuse-sample-java-war-hello-master
        target: /opt/boxfuse
