version: "3.3"
services:
  build_app:
    build: .
    volumes:
      - type: volume
        source: warnic
        target: /mnt

  tomcat:
    image: tomcat:7.0.72-alpine
    ports:
      - "5555:8080"
    volumes:
      - type: volume
        source: warnic
        target: /usr/local/tomcat/webapps
    depends_on:
      - build_app
volumes:
  warnic:

