version: "3.3"
services:
  build_app:
    build: .
    volumes:
      - type: volume
        source: warnic
        target: /mnt

  tomcat:
    image: tomcat:9-jre11-openjdk-slim-buster
    ports:
      - "5555:8080"
    volumes:
      - type: volume
        source: warnic
        target: /usr/local/tomcat/webapps
    depens_on:
      - build_app
volumes:
  warnic:

